# Generated by Django 2.2 on 2019-04-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='map_server.PosterGroup'),
        ),
    ]
