# Generated by Django 2.2 on 2019-04-14 09:56

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PosterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PosterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('admins', models.ManyToManyField(related_name='group_admin', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='group_member', to=settings.AUTH_USER_MODEL)),
                ('poster_types', models.ManyToManyField(to='map_server.PosterType')),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map_server.PosterGroup')),
                ('poster_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posters', to='map_server.PosterType')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posters', to='map_server.PosterStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
